### ISSUE TITLE
Performance decline

### ISSUE THREAD

**Issue by tju-zxy** [TaoHuang95/DGSMP#2]
Thanks for your great work! However, when I reproduce your results with your pretrained weights, I only get the results of 31.9 dB (PSNR). The result in the paper is 32.6 dB. Could you help me discover my problem? Thanks a lot.

**Comment by TaoHuang95** [comment]
The PSNR and SSIM results of all competing methods in the paper were computed using this code (https://github.com/TaoHuang95/DGSMP/tree/main/Simulation/Quality_Metrics).

**Comment by tju-zxy** [comment]
Thanks for your help! I have solved this problem.
