### ISSUE TITLE
Real Training Data

### ISSUE THREAD

**Issue by linjing7** [TaoHuang95/DGSMP#4]
Hi, thank you very much for your excellent work.  The code about the real HSI is published. However, there is no training data, so could you please share the training data with us? Or could you please tell me how to generate the training data? Thank you very much.

**Comment by TaoHuang95** [comment]
See the readme file. https://github.com/TaoHuang95/DGSMP/blob/main/README.md

**Comment by linjing7** [comment]
Okay, thank you very much.
