### ISSUE TITLE
Spectral Interpolation. 

### ISSUE THREAD

**Issue by linjing7** [TaoHuang95/DGSMP#5]
Hi, I notice that both the original CAVE and KAIST have 31 spectral channels, so I wonder how do you interpolate it into 28 spectral channels? Could you please offer me the code?  Thank you very much !

**Comment by TaoHuang95** [comment]
Hi, for generating the training dataset, we used a spectral interpolation method ('interp1' in Matlab) for each pixels of original CAVE dataset with 31 channels to generate 28 channels at range of 450-650nm.

The training dataset with 28 channels can be found in the readme file. https://github.com/TaoHuang95/DGSMP/blob/main/README.md
