### ISSUE TITLE
The detailed performance of DGSMP with stage number = 1,2,3,5,6,7,9

### ISSUE THREAD

**Issue by caiyuanhao1998** [TaoHuang95/DGSMP#6]
This repo is amazing. Thanks for your effort in open-source contribution.

Our recent work has cited your paper.

To make a more detailed comparison with DGSMP, could you please share the performance (PSNR / SSIM) of DGSMP with the stage number (T in your original paper) = 1, 2, 3, 5, 6, 7, 9

Thanks for any responses

**Comment by TaoHuang95** [comment]
OK.

- T=1: PSNR-31.75, SSIM-0.9065;
- T=2: PSNR-32.10, SSIM-0.9061;
- T=3: PSNR-32.32, SSIM-0.9174;
- T=4: PSNR-32.63, SSIM-0.9166;
- T=5: PSNR-32.74, SSIM-0.9239;
- T=6: PSNR-32.93, SSIM-0.9214.

**Comment by caiyuanhao1998** [comment]
What about T = 7, 8, 9 ?

**Comment by TaoHuang95** [comment]
We haven't done the experiments with T > 6.

**Comment by caiyuanhao1998** [comment]
All right, thank you!
