### ISSUE TITLE
About RGB Image

### ISSUE THREAD

**Issue by XinranQin** [TaoHuang95/DGSMP#7]
How to get the RGB image of HSI?

**Comment by TaoHuang95** [comment]
https://github.com/TaoHuang95/DGSMP/tree/main/RGB%20Images

**Comment by XinranQin** [comment]
Thank you for replay



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月06日 01:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TaoHuang95/DGSMP] About RGB Image (Issue #7) |

https://github.com/TaoHuang95/DGSMP/tree/main/RGB%20Images

**Comment by Williamgithub1** [comment]
First of all, thank you and your team for their excellent work. In real test，We don't find RGB of the first two pictures in the link you gave，Could you please provide us with the RGB image of scene1and scene2 ？
