### ISSUE TITLE
RGB Image

### ISSUE THREAD

**Issue by Williamgithub1** [TaoHuang95/DGSMP#8]
First of all, thank you and your team for their excellent work. In real test，We don't find RGB of the first two pictures in the link you gave，Could you please provide us with the RGB image of scene1and scene2 ？

**Comment by TaoHuang95** [comment]
OK. I have added the RGB images of scene1and scene2 in this link (https://github.com/TaoHuang95/DGSMP/blob/main/RGB%20Images/Scenes_RGB.pptx).

**Comment by Williamgithub1** [comment]
Thank you very much,Wish you a happy life！

**Comment by Williamgithub1** [comment]
Excuse me, the first picture is very blurred in my view. Is it HD when you upload it？

**Comment by TaoHuang95** [comment]
Sorry! I have updated this file. ( https://github.com/TaoHuang95/DGSMP/blob/main/RGB%20Images/Scenes_RGB.pptx )
